Connect to aws using node

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,6 +2,9 @@
 
 set -e
 unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
 
 
 indent() {
@@ -22,6 +25,8 @@ FILE_NAME="`cat $1/vco-backup`"
 #mv /tmp/${FILE_NAME}.tgz $1
 
 
+
+
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
@@ -32,6 +37,24 @@ echo "Build dir: ${BUILD_DIR}"
 echo "Cache dir: ${CACHE_DIR}"
 echo "Env dir: ${ENV_DIR}"
 echo "BP dir: ${BP_DIR}"
+
+### Load dependencies
+source ${BP_DIR}/lib/output.sh
+
+### Upload with Node
+npm install | output "$LOG_FILE"
+
+
+BUILD_DIR=${BUILD_DIR} \
+CACHE_DIR=${CACHE_DIR} \
+ENV_DIR=${ENV_DIR} \
+SOURCE_VERSION=${SOURCE_VERSION} \
+node ${BP_DIR}/lib/upload.js | output "$LOG_FILE"
+
+
+
+
+
 
 
 
